### ISSUE TITLE
登录时的验证码图片问题

### ISSUE THREAD

**Issue by jinfukang** [insistence/RuoYi-Vue-FastAPI#1]
![企业微信截图_17089336692433](https://github.com/insistence/RuoYi-Vue-FastAPI/assets/67544423/fa82d1c5-49fd-43da-bae6-a73eadca472a)
原代码为24行所示，但运行项目会报redis.exceptions.ResponseError: wrong number of arguments for 'set' command
我理解可能是set传入的参数数量不对，多了ex参数，我将ex去掉
修改后的代码如25行所示，但运行项目后，前端页面压根不展示验证码那一行了
实在是找不到问题所在了，求助，谢谢

**Comment by insistence** [comment]
建议检查一下你的redis版本，我这边使用的是3.2.100，可以使用>=3.2.100的版本

**Comment by jinfukang** [comment]
> 建议检查一下你的redis版本，我这边使用的是3.2.100，可以使用>=3.2.100的版本

我看项目里的Redis是5.0.1，我本地也是5.0.1，或者我试试你的版本3.2.100

**Comment by insistence** [comment]
是redis应用的版本，不是redis库

**Comment by jinfukang** [comment]
> 是redis应用的版本，不是redis库

谢谢大哥，成功了，我继续啃代码了，多谢大佬多谢多谢多谢多谢多谢多谢多谢多谢多谢
