### ISSUE TITLE
编译器注入爆红, 有解决办法吗?

### ISSUE THREAD

**Issue by over35to70icanmakemore** [insistence/RuoYi-Vue-FastAPI#2]
比如, py文件抬头有类似from **module_admin**.service.login_service import *类似java class注入的申明, 但是PyCharm 2023.2.5给module_admin标记爆红了, 这种一般是编译器智能识别失败了但是不影响启动运行, 有解决办法吗?谢谢

**Comment by insistence** [comment]
可以把backend作为项目打开

**Comment by over35to70icanmakemore** [comment]
backend为项目目录打开确实没有问题了
