### ISSUE TITLE
修改Admin账号的密码的时候提示 该admin列有了 

### ISSUE THREAD

**Issue by qq923004243** [insistence/RuoYi-Vue-FastAPI#3]
上面是一个问题哈，下面是我在使用框架的时候发现的，连接池是默认的不太够用，可以这么初始化然后在配置文件里面配置。
database.py
engine = create_engine(
    SQLALCHEMY_DATABASE_URL, echo=DataBaseConfig.db_echo,pool_size=200,max_overflow=300,pool_recycle=3600
)

**Comment by insistence** [comment]
感谢反馈，修改密码的问题已修复，已推送至develop分支。数据库连接的问题我后续会在配置文件中增加这几项配置。
