### ISSUE TITLE
分页

### ISSUE THREAD

**Issue by Shen7me** [insistence/RuoYi-Vue-FastAPI#5]
超过10的分页，页数一直是默认1

**Comment by insistence** [comment]
这个是fastapi0.115.0的bug，已经给官方提issue了，等fastapi修复更新下版本就可以了，目前可以参考1.3.3的版本的写法，那个是正常的

**Comment by insistence** [comment]
或者直接使用1.3.3版本

**Comment by insistence** [comment]
1.5.0版本查询参数模型声明方式已回滚至1.3.3版本的用法，升级至1.5.0版本即可解决
